dist: xenial
services:
  - xvfb
addons:
  apt:
    packages:
    - libxkbcommon-x11-0

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"

env:
  - QT_DEBUG_PLUGINS=1

script:
  - "python run_checks_and_format.py"
  - "xvfb-run -a pytest -sv tests/ --cov=qtsass"

after_success:
  - "codecov"
