language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"

script:
  - "python run_checks_and_format.py"
  - "pytest tests/ --cov=qtsass"

after_success:
  - "codecov"
