language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install codecov pytest pytest-cov"

script:
  - "pytest tests/ --cov=qtsass"

after_success:
  - "codecov"
