build: off

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -r requirements.txt"
  - "pip install pytest"

test_script:
  - "pytest tests/"
